// src/app/commit-viewer/commit-viewer.component.ts
import { commitViewerLoaded } from '../actions/git-data.actions';
import { State } from './../store/index';
import { Component, ElementRef, OnInit } from '@angular/core';
import { Store } from '@ngrx/store';

@Component({
  selector: 'app-commit-viewer',
  templateUrl: './commit-viewer.component.html',
  styles: [
  ]
})
export class CommitViewerComponent implements OnInit {

  constructor(private store: Store<State>) { }

  ngOnInit(): void {
    // this.store.dispatch(loadCommits({ repoPath: '/home/dsm6069/dev/DealSimple/' }));
    // this.store.dispatch(loadRepoBranches({ repoPath: '/home/dsm6069/dev/DealSimple/' }));
    this.store.dispatch(commitViewerLoaded({ repoPath: '/home/dsm6069/dev/DealSimple/' }));
  }

}

<div class="hstack px-0 mt-1">
  <div class="mx-0 row align-items-start flex-nowrap" style="overflow-x: hidden;">
    <div class="px-0 col-auto">
      <app-graph></app-graph>
    </div>
    <div class="px-0 col-auto">
      <app-table></app-table>
    </div>
  </div>
</div>

// src/components/CommitViewer.vue
<template>
  <div class="htstack px-0">
    <div class="mx-0 row align-items-start flex-nowrap" style="overflow-x: hidden; width: 100%">
      <div class="px-0 col-auto">
        <commit-graph></commit-graph>
      </div>
      <div class="px-0">
        <!-- Table -->
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { invoke } from '@tauri-apps/api';
import CommitGraph from './CommitGraph.vue';

export default {
  components: {
    CommitGraph
  },
  mounted() {

    invoke('get_changes', { repoPath: '/home/notnight/dev/beekeeper-studio/' });
  }
};
</script>
